Repository rinikerlab/lightweight-registration, pull requests merged in 2023-05, with the labels that each got.

#14 Fixing problem with stripping salts during standardization
  lwreg/utils.py
Labels: bug

#16 Add standardization lib and allow chaining standardization functions
  README.md
  lwreg/standardization_lib.py
  lwreg/test_lwreg.py
  lwreg/utils.py
Labels: enhancement

#24 Fixes #22
  lwreg/standardization_lib.py
  lwreg/test_lwreg.py
  lwreg/utils.py
Labels: enhancement

#27 a collection of changes
  demos/01_registration_basics.ipynb
  demos/02_computational_experiment_1.ipynb
  demos/demo_data/S1P1_data.csv
  lwreg/__init__.py
  lwreg/test_lwreg.py
  lwreg/utils.py
Labels: documentation, enhancement
